'use strict';
const CT_EN = Object.freeze({
  "Выберите подходящий тариф. После активации доступа здесь появится подключение.": "Choose a plan. Connection details will appear here once access is activated.",
  "Лимит появится после выбора тарифа.": "Your allowance will appear after you choose a plan.",
  "Инструкции по установке и подключению.": "Installation and connection guides.",
  "Ответы на вопросы и помощь с подключением.": "Answers to your questions and help connecting.",
  "Оформление:": "Theme:",
  ". Изменить тему": ". Change theme",
  "тёмное": "dark",
  "светлое": "light",
  "Оформление": "Appearance",
  "Выберите удобную тему. В автоматическом режиме оформление меняется вместе с Telegram или устройством.": "Choose a theme. Automatic mode follows Telegram or your device settings.",
  "Тема приложения": "App theme",
  "Автоматически": "Automatic",
  "Как в Telegram или на устройстве": "Match Telegram or your device",
  "Светлая": "Light",
  "Светлые карточки и мягкие тени": "Light cards and soft shadows",
  "Тёмная": "Dark",
  "Мягкий контраст на тёмном фоне": "Gentle contrast on a dark background",
  "Без лимита устройств": "Unlimited devices",
  "устройство": "device",
  "устройства": "devices",
  "устройств": "devices",
  "день": "day",
  "дня": "days",
  "дней": "days",
  "Б": "B",
  "КБ": "KB",
  "МБ": "MB",
  "ГБ": "GB",
  "ТБ": "TB",
  "Бессрочно": "No expiry",
  "Активна": "Active",
  "Истекла": "Expired",
  "Лимит трафика": "Traffic limit reached",
  "Отключена": "Disabled",
  "Оплачен": "Paid",
  "Ожидает оплаты": "Awaiting payment",
  "Не оплачен": "Unpaid",
  "Возвращён": "Refunded",
  "Отменён": "Cancelled",
  "Ждёт ответа": "Awaiting a reply",
  "В работе": "In progress",
  "Закрыто": "Closed",
  "Войдите по коду доступа": "Sign in with your access code",
  "Сеанс завершён. Закройте Mini App и откройте его из бота заново.": "Your session has ended. Close the Mini App and reopen it from the bot.",
  "Запрос не выполнен": "The request could not be completed",
  "Сервер долго отвечает. Проверьте соединение и повторите.": "The server is taking too long to respond. Check your connection and try again.",
  "Не удалось загрузить": "Unable to load",
  "Повторить": "Try again",
  "Открыть бота": "Open bot",
  "Написать в поддержку": "Contact support",
  "Ссылка недоступна. Обратитесь в поддержку.": "This link is unavailable. Please contact support.",
  "Ссылка скопирована": "Link copied",
  "Скопировать ссылку": "Copy link",
  "Ссылка для копирования": "Link to copy",
  "Нажмите на ссылку, выделите её и скопируйте.": "Select the link and copy it.",
  "Закрыть окно": "Close window",
  "Подписка": "Subscription",
  "Тарифы": "Plans",
  "Платежи": "Payments",
  "Друзья": "Friends",
  "Помощь": "Help",
  "Нет доступа": "No access",
  "Истекает сегодня": "Expires today",
  "Управление подпиской": "Manage subscription",
  "Устройства": "Devices",
  "Израсходовано": "Used",
  "Обновится": "Resets on",
  "Нет подписки": "No subscription",
  "· до": "· until",
  "Выберите тариф или обратитесь в поддержку": "Choose a plan or contact support",
  "Трафик безлимитный": "Unlimited traffic",
  "осталось": "remaining",
  "из": "of",
  "Использовано трафика": "Traffic used",
  "Мои устройства": "My devices",
  "Подключиться": "Connect",
  "Ссылку вставляют в приложение VPN. Кнопка «Подключиться» откроет страницу, где приложение подберётся под ваше устройство.": "Import the link into your VPN app. Select Connect to find an app for your device.",
  "Выбрать тариф": "Choose a plan",
  "Обратиться в поддержку": "Contact support",
  "Подписка, подключение и помощь — в одном месте.": "Your subscription, connection and help in one place.",
  "Подписка скоро закончится. Продлите её заранее, чтобы сохранить доступ.": "Your subscription expires soon. Renew it in advance to keep your access.",
  "История платежей": "Payment history",
  "Обновить данные": "Refresh data",
  "Автопродление": "Auto-renewal",
  "Продление сохранённым способом оплаты. Если автосписание недоступно, бот напомнит об оплате.": "Renew using your saved payment method. If automatic charging is unavailable, the bot will remind you to pay.",
  "Продлить или сменить тариф": "Renew or change plan",
  "Автопродление включено": "Auto-renewal enabled",
  "Автопродление выключено": "Auto-renewal disabled",
  "Удаление освобождает место. Если устройство продолжит обновлять подписку, оно зарегистрируется снова.": "Removing a device frees up a slot. If it continues refreshing the subscription, it will register again.",
  "Последний запрос:": "Last request:",
  "Отвязать устройство": "Remove device",
  "Устройство": "Device",
  "Платформа неизвестна": "Unknown platform",
  "Версия неизвестна": "Unknown version",
  "Устройств пока нет. Они появятся после первого подключения.": "No devices yet. They will appear after your first connection.",
  "Отвязать это устройство от подписки?": "Remove this device from your subscription?",
  "Устройство отвязано": "Device removed",
  "Загружаем тарифы…": "Loading plans…",
  "После подтверждения оплаты доступ включится.": "Access will activate after payment is confirmed.",
  "Пробный": "Trial",
  "за": "for",
  "Безлимитный трафик": "Unlimited traffic",
  "Бесплатно": "Free",
  "Тарифы пока не опубликованы. Напишите в поддержку.": "No plans have been published yet. Please contact support.",
  "Срок подключения": "Subscription term",
  "Введите код": "Enter code",
  "Промокод": "Promo code",
  "необязательно": "optional",
  "Применить": "Apply",
  "Выберите срок подписки": "Choose a subscription term",
  "К оплате": "Total due",
  "Срок с бонусом:": "Term including bonus:",
  "дн.": "days",
  "Получить бесплатно": "Activate for free",
  "Оплатить": "Pay",
  "Оплатить ·": "Pay ·",
  "Оформить счёт ·": "Create invoice ·",
  "Оплата временно недоступна. Напишите в поддержку — вам помогут с подключением.": "Payments are temporarily unavailable. Contact support for help getting connected.",
  "Промокод применён": "Promo code applied",
  "Цена без промокода": "Price without promo code",
  "Сначала примените промокод, чтобы увидеть итоговую сумму.": "Apply the promo code first to see the total.",
  "Готовим счёт…": "Preparing your invoice…",
  "Доступ включён. Обновите подписку.": "Access activated. Refresh your subscription.",
  "Счёт создан. Он доступен в разделе «Платежи».": "Invoice created. You can find it in Payments.",
  "Доступ включён": "Access activated",
  "Счёт №": "Invoice #",
  "Проверить оплату": "Check payment",
  "Открыть оплату": "Open payment",
  "После оплаты вернитесь сюда и нажмите «Проверить оплату».": "After paying, return here and select Check payment.",
  "Сообщите номер счёта в поддержку. После подтверждения оплаты нажмите «Проверить оплату».": "Send the invoice number to support. Once payment is confirmed, select Check payment.",
  "Используйте реквизиты из счёта или напишите в поддержку": "Use the payment details on your invoice or contact support",
  "Оплата отменена. Счёт можно открыть снова.": "Payment cancelled. You can reopen the invoice.",
  "Вернитесь к счёту, чтобы проверить оплату.": "Return to the invoice to check your payment.",
  "Оплачено. Пакет сохранён и включится после активации подходящей подписки.": "Paid. Your add-on is saved and will activate when an eligible subscription becomes active.",
  "Оплата подтверждена. Подписка обновлена.": "Payment confirmed. Your subscription has been updated.",
  "Загружаем историю…": "Loading history…",
  "Счета и история оплаты вашей подписки.": "Invoices and payment history for your subscription.",
  "Оплата подписки": "Subscription payment",
  "Продолжить оплату": "Continue payment",
  "Платежей пока нет.": "No payments yet.",
  "Показать ещё": "Show more",
  "Загружаем приглашения…": "Loading referrals…",
  "Пригласить друга": "Invite a friend",
  "с оплат приглашённых клиентов": "of payments made by people you invite",
  "Пришло": "Joined",
  "Начислено": "Earned",
  "К выплате": "Available for payout",
  "По вопросам выплаты напишите в поддержку.": "Contact support to request a payout.",
  "Ваша ссылка": "Your link",
  "Ссылка появится после запуска бота.": "Your link will appear once the bot is running.",
  "Приглашения пока отключены.": "Referrals are currently disabled.",
  "Загружаем поддержку…": "Loading support…",
  "Документы и условия сервиса": "Documents and terms of service",
  "Мои обращения": "My tickets",
  "Новые обращения отключены. История переписки доступна ниже.": "New tickets are disabled. Your conversation history is available below.",
  "Обращений пока нет.": "No tickets yet.",
  "← К обращениям": "← Back to tickets",
  "Новое обращение": "New ticket",
  "Предыдущие сообщения": "Earlier messages",
  "Поддержка": "Support",
  "Вы": "You",
  "Обращение закрыто. Если нужна помощь, создайте новое.": "This ticket is closed. Open a new ticket if you need help.",
  "Напишите сообщение": "Write a message",
  "Отправить сообщение": "Send message",
  "Что случилось?": "What happened?",
  "Ваш ответ": "Your reply",
  "Новые сообщения отключены администратором.": "New messages have been disabled by the administrator.",
  "Сообщение отправлено": "Message sent",
  "Расширить подписку": "Extend your limits",
  "Без смены тарифа": "Keep your current plan",
  "Добавить трафик": "Add traffic",
  "Добавить устройства": "Add devices",
  "Мои докупки": "My add-ons",
  "Загрузить доступные докупки": "Load available add-ons",
  "Действует до": "Valid until",
  "На срок действующей подписки": "For the current subscription term",
  "Загружаем пакеты…": "Loading add-ons…",
  "Срок самой подписки не меняется.": "Your subscription expiry date stays the same.",
  "Дополнительный трафик прибавится к лимиту и действует до ближайшего сброса или окончания подписки.": "Additional traffic increases your limit until the next reset or your subscription expires.",
  "Дополнительные места действуют до конца текущего оплаченного срока. При продлении они не продлеваются автоматически.": "Additional device slots last until the end of your current paid term. They do not renew automatically.",
  "Оплаченные пакеты и их сроки действия.": "Purchased add-ons and their expiry dates.",
  "Для текущей подписки нет доступных пакетов. Проверьте тариф или обратитесь в поддержку.": "No add-ons are available for your current subscription. Check your plan or contact support.",
  "Уже оплачено": "Already purchased",
  "устр.": "devices",
  "Ожидает действующую подписку": "Waiting for an active subscription",
  "Пакет добавится после подтверждения оплаты. Тариф и срок подписки останутся прежними.": "Your add-on will activate once payment is confirmed. Your plan and expiry date stay the same.",
  "Другие пакеты": "Other add-ons",
  "Оплата пока не настроена. Обратитесь в поддержку.": "Payments have not been configured yet. Please contact support.",
  "Счёт создан. Он доступен в истории платежей.": "Invoice created. You can find it in your payment history.",
  "Если оплата поступит после окончания подписки, пакет сохранится и включится после её активации.": "If payment arrives after your subscription expires, the add-on will be saved and will activate when your subscription becomes active.",
  "Перейти к оплате": "Proceed to payment",
  "Аккаунт": "Account",
  "Ваш кабинет": "Your account",
  "Главная": "Home",
  "Пригласить": "Invite",
  "Кабинет": "Account",
  "Выйти": "Sign out",
  "Тарифы и покупки": "Plans and purchases",
  "Приглашения": "Referrals",
  "Подключим ваше устройство": "Let’s connect your device",
  "Закончился трафик": "You’ve used all your traffic",
  "Доступ приостановлен": "Access suspended",
  "Продлим вашу подписку": "Let’s renew your subscription",
  "Начнём с выбора тарифа": "Let’s choose a plan",
  "Установите приложение и подключитесь к защищённой сети": "Install the app and connect to the secure network",
  "Дождитесь обновления лимита или выберите дополнительный пакет.": "Wait for your limit to reset or choose a traffic add-on.",
  "Обратитесь в поддержку, чтобы уточнить причину.": "Contact support to find out why.",
  "Выберите подходящий срок и количество устройств. После оплаты здесь появится подключение.": "Choose your subscription term and number of devices. Connection details will appear here after payment.",
  "Этапы подключения": "Connection steps",
  "Используется устройств": "Devices in use",
  "Добавить": "Add",
  "Трафик": "Traffic",
  "Докупить": "Buy more",
  "трафик": "traffic",
  "Ваша подписка": "Your subscription",
  "Код доступа": "Access code",
  "Управление": "Manage",
  "Управление доступом": "Manage access",
  "Нужна помощь с подключением?": "Need help connecting?",
  "Инструкции, ответы на вопросы и поддержка.": "Guides, answers and support.",
  "Открыть инструкции": "Open guides",
  "Подписка не оформлена": "No subscription yet",
  "Посмотреть пакеты": "View add-ons",
  "Тариф": "Plan",
  "Доступ": "Access",
  "Подключение": "Connection",
  "без лимита": "unlimited",
  "Безлимит": "Unlimited",
  "Нет данных": "No data",
  "Без ограничения трафика": "Unlimited traffic",
  "Выберите тариф": "Choose a plan",
  "Осталось": "Remaining",
  "Не оформлена": "Not subscribed",
  "Нет тарифа": "No plan",
  "до": "until",
  "Без ограничения срока": "No expiry date",
  "Доступ появится после оформления": "Access will appear after subscribing",
  "Продлить": "Renew",
  "Ваш трафик": "Your traffic",
  "У тарифа нет ограничения трафика.": "Your plan includes unlimited traffic.",
  "Лимит обновится": "Your limit resets on",
  "Докупить трафик": "Buy more traffic",
  "Повторить загрузку докупок": "Retry loading add-ons",
  "Код доступа к сайту": "Website access code",
  "Скопировать ссылку подключения": "Copy connection link",
  "Связать с Telegram": "Link Telegram account",
  "Выйти из всех сеансов сайта": "Sign out of all website sessions",
  "Подтвердите привязку в боте, затем обновите кабинет.": "Confirm the link in the bot, then refresh your account.",
  "Загружаем код доступа…": "Loading access code…",
  "Заменить код доступа": "Replace access code",
  "Старый код перестанет работать, остальные сеансы сайта завершатся. Подписка и покупки сохранятся.": "The old code will stop working and other website sessions will end. Your subscription and purchases will be kept.",
  "Выпустить новый код": "Generate a new code",
  "Этот код был создан до появления повторного просмотра.": "This code was created before repeat viewing was introduced.",
  "Введите его один раз — после этого вы сможете смотреть и копировать его здесь.": "Enter it once to enable viewing and copying it here.",
  "Войдите на сайт по вашему коду — после этого он будет доступен здесь. Или выпустите новый код для этого же аккаунта.": "Sign in to the website using your code to make it available here. Or generate a new code for this account.",
  "Ваш код доступа": "Your access code",
  "Сохранить для просмотра": "Save for viewing",
  "Код не подошёл. Проверьте символы и попробуйте ещё раз.": "The code did not match. Check the characters and try again.",
  "Получите код, чтобы входить на сайт в этот же аккаунт. Подписка и покупки будут общими с Telegram.": "Get a code to sign in to this account on the website. Your subscription and purchases will be shared with Telegram.",
  "Получить код": "Get access code",
  "Заменить код? Старый код перестанет работать, остальные сеансы сайта завершатся.": "Replace your code? The old code will stop working and other website sessions will end.",
  "Для замены введите текущий код. Если он потерян, выпустите новый в привязанном Mini App.": "Enter your current code to replace it. If it is lost, generate a new one in your linked Mini App.",
  "Этот код открывает ваш аккаунт. Сохраните его и не передавайте другим.": "This code grants access to your account. Save it and do not share it with anyone.",
  "Скопировать код": "Copy code",
  "Скачать": "Download",
  "Я сохранил код доступа": "I have saved my access code",
  "Перейти в кабинет": "Open my account",
  "Скрыть код": "Hide code",
  "Код можно посмотреть снова в разделе «Код доступа».": "You can view your code again in Access code.",
  "Код скопирован": "Code copied",
  "Код скопирован в буфер обмена.": "Code copied to clipboard.",
  "Не удалось скопировать. Выделите код и скопируйте его вручную.": "Unable to copy. Select the code and copy it manually.",
  "Код доступа:": "Access code:",
  "Храните код в безопасном месте.": "Keep your code in a safe place.",
  "Файл с кодом подготовлен для скачивания.": "Your code file is ready to download.",
  "Показать код": "Show code",
  "Сохраните код доступа": "Save your access code",
  "Сохраните код": "Save your code",
  "Сохраните код, с которым вы вошли. Если не успели его записать, выпустите новый.": "Save the code you used to sign in. If you did not write it down, generate a new one.",
  "Код сохранён": "Code saved",
  "Получить новый код": "Get a new code",
  "Войти в кабинет": "Sign in to your account",
  "Введите код доступа из Mini App или код, который получили при регистрации на сайте.": "Enter your Mini App access code or the code you received when registering on the website.",
  "Войти": "Sign in",
  "Где взять код или как восстановить доступ?": "Where can I find my code or recover access?",
  "Откройте Mini App бота и нажмите «Код доступа». В нём можно посмотреть код вашего аккаунта или выпустить новый.": "Open the bot’s Mini App and select Access code to view your code or generate a new one.",
  "Зарегистрироваться": "Register",
  "Код не подошёл. Проверьте его и попробуйте ещё раз.": "The code did not match. Check it and try again.",
  "· Безлимитный трафик": "· Unlimited traffic",
  "О сайте": "About this website",
  "Войти по коду": "Sign in with a code",
  "У меня уже есть код": "I already have a code",
  "Как подключиться": "How to connect",
  "Сейчас нет доступных тарифов.": "No plans are available at the moment.",
  "Обновить": "Refresh",
  "Загружаем подписку…": "Loading subscription…",
  "Разделы": "Sections",
  "Язык": "Language",
  "Содержимое на английском ещё не опубликовано.": "English content has not been published yet.",
  "не найдено": "Not found",
  "требуется вход": "Please sign in or check your access code",
  "превышен лимит запросов; повторите позже": "Too many requests. Please try again later",
  "недостаточно прав": "This action is not allowed",
  "внутренняя ошибка": "Internal error. Please try again later",
  "Аккаунт уже создан. Войдите по сохранённому коду": "Your account already exists. Sign in with your saved code",
  "Обновите страницу регистрации": "Refresh the registration page",
  "Бот для привязки не настроен": "Telegram linking has not been configured",
  "Сайт ещё не опубликован": "The website has not been published yet",
  "Регистрация отключена": "Registration is disabled",
  "Нет кода? Создайте аккаунт и сохраните свой код доступа.": "No code yet? Create an account and save your access code.",
  "Регистрация на сайте сейчас закрыта. Если у вас уже есть аккаунт, войдите по коду. Для нового подключения обратитесь в поддержку.": "Website registration is currently closed. If you already have an account, sign in with your code. To get started as a new customer, contact support.",
  "Сначала сохраните код доступа": "Save your access code first",
  "Покупки на сайте отключены": "Purchases are disabled on this website",
  "Покупки в приложении отключены. Откройте бота или напишите в поддержку": "Purchases are disabled in the app. Open the bot or contact support",
  "Промокод не найден": "Promo code not found",
  "Сообщение должно содержать от 1 до 4000 символов": "The message must contain 1 to 4,000 characters",
  "Новые сообщения в обращениях отключены. Используйте ссылку на поддержку": "Ticket messages are disabled. Please use the support link",
  "обращение закрыто": "This support ticket is closed",
  "Цена не найдена": "Price not found",
  "цена не найдена": "Price not found",
  "оформление временно недоступно": "Checkout is temporarily unavailable",
  "Подтвердите сброс кода доступа": "Confirm the access code reset"
});
